export const GLYPH_PLATE = {
  ChartBar: "tile-1",
  ChartLine: "tile-1",
  ChartLineUp: "tile-1",
  Pulse: "tile-1",
  TrendUp: "tile-1",
  TrendDown: "tile-1",
  ChartPie: "tile-4",
  ChartPieSlice: "tile-4",
  Percent: "tile-4",

  Buildings: "tile-2",
  Folder: "tile-2",
  Tag: "tile-2",
  Kanban: "tile-2",
  Stack: "tile-2",
  Users: "tile-2",
  UsersThree: "tile-2",
  User: "tile-2",
  UserCircle: "tile-2",
  Student: "tile-2",

  Clock: "tile-3",
  ClockCounterClockwise: "tile-3",
  Timer: "tile-3",
  Hourglass: "tile-3",
  CalendarBlank: "tile-3",
  Calendar: "tile-3",
  Lightning: "tile-3",

  Robot: "tile-5",
  Sparkle: "tile-5",
  MagicWand: "tile-5",
  Brain: "tile-5",
  FlowArrow: "tile-5",
  GitBranch: "tile-5",
  Lightbulb: "tile-5",

  Megaphone: "tile-brand",
  PaperPlaneTilt: "tile-brand",
  ChatCircle: "tile-brand",
  ChatCircleDots: "tile-brand",
  ChatsCircle: "tile-brand",
  EnvelopeSimple: "tile-brand",
  Rocket: "tile-brand",
  Target: "tile-brand",

  Wallet: "tile-3",
  CurrencyDollar: "tile-3",
  Money: "tile-3",
  Receipt: "tile-3",
  CreditCard: "tile-3",
  Invoice: "tile-3",

  CheckCircle: "tile-healthy",
  Check: "tile-healthy",
  SealCheck: "tile-healthy",
  ShieldCheck: "tile-healthy",
  Warning: "tile-warning",
  WarningCircle: "tile-warning",
  WarningOctagon: "tile-fault",
  XCircle: "tile-fault",
  Trash: "tile-fault",
  Prohibit: "tile-fault",
  Info: "tile-info",
  Question: "tile-info",

  Gear: "tile-neutral",
  GearSix: "tile-neutral",
  Wrench: "tile-neutral",
  Plug: "tile-neutral",
  PlugsConnected: "tile-neutral",
  Key: "tile-neutral",
  Lock: "tile-neutral",
  Database: "tile-neutral",
  Code: "tile-neutral",
  Webhooks: "tile-neutral",
  FileText: "tile-neutral",
  Files: "tile-neutral",
  Book: "tile-neutral",
  BookOpen: "tile-neutral",
} as const;

export type GlyphName = keyof typeof GLYPH_PLATE;

export function glyphPlate(name: string): string {
  return GLYPH_PLATE[name as GlyphName] ?? "tile-neutral";
}
